"""Mermaid diagram post-processing.

Provides 13 fix types to repair common Mermaid syntax issues generated by LLMs.
Uses an extract-fix-reassemble strategy: extract all mermaid blocks, fix each
one independently, then reassemble into the original document.
"""

from __future__ import annotations


import html
import re

# Pattern to match fenced mermaid code blocks
_MERMAID_BLOCK_RE = re.compile(
    r"(```mermaid\s*\n)(.*?)(```)",
    re.DOTALL,
)

# Pattern for flowchart nodes with unquoted parentheses
_UNQUOTED_PAREN_NODE_RE = re.compile(
    r'(\w+)\[([^\]]*?)\(([^)]*?)\)([^\]]*?)\]'
)

# Pattern for diamond nodes with unquoted parentheses
_UNQUOTED_PAREN_DIAMOND_RE = re.compile(
    r'(\w+)\{([^\]]*?)\(([^)]*?)\)([^\}]*?)\}'
)

# Pattern for edge labels with unquoted parentheses
_UNQUOTED_PAREN_EDGE_RE = re.compile(
    r'\|([^\|]*?)\(([^)]*?)\)([^\|]*?)\|'
)

# Pattern for assignment operator in diamond conditions
_ASSIGN_IN_DIAMOND_RE = re.compile(
    r'(\w+)\{([^}]*?)\s*=\s*([^}]*?)\}'
)

# Pattern for assignment operator in bracket labels
_ASSIGN_IN_BRACKET_RE = re.compile(
    r'(\w+)\[([^\]]*?)\s*=\s*([^\]]*?)\]'
)

# Reserved word "end" as a node ID in flowcharts
_RESERVED_END_RE = re.compile(
    r'^(\s*)(end)(\s*[\[{|(]|$)',
    re.MULTILINE,
)

# Mermaid/o/x markers after --- in flowcharts
_STYLE_AFTER_DIVIDER_RE = re.compile(
    r'(---+)\s*([ox])\s*$',
    re.MULTILINE,
)

# Nested quotes in sequence diagrams
_NESTED_QUOTES_RE = re.compile(
    r'"([^"]*?)"([^"]*?)"([^"]*?)"'
)

# Semicolons in sequence diagram messages
_SEMICOLON_IN_MSG_RE = re.compile(
    r'(->>|-->>)\s*(.*?)\s*;'
)


def fix_mermaid_syntax(content: str) -> str:
    """Extract all mermaid blocks, fix each one, and reassemble.

    Args:
        content: Document content containing fenced mermaid code blocks.

    Returns:
        Content with all mermaid blocks fixed and wrapped in <details>.
    """
    blocks: list[tuple[str, str, str]] = []
    for m in _MERMAID_BLOCK_RE.finditer(content):
        blocks.append((m.group(1), m.group(2), m.group(3)))

    if not blocks:
        return content

    # Build replacement map
    replacements: dict[str, str] = {}
    for prefix, block_body, suffix in blocks:
        fixed = _fix_single_mermaid_block(block_body)
        full_block = f"{prefix}{fixed}{suffix}"
        original = f"{prefix}{block_body}{suffix}"
        replacements[original] = full_block

    result = content
    for original, fixed in replacements.items():
        result = result.replace(original, fixed, 1)

    # Wrap all mermaid blocks in <details>
    result = _wrap_mermaid_in_details(result)

    return result


def _fix_single_mermaid_block(block: str) -> str:
    """Fix all syntax issues in a single mermaid block body.

    Args:
        block: The body of a mermaid code block (without fences).

    Returns:
        Fixed mermaid block body.
    """
    lines = block.split("\n")
    fixed_lines: list[str] = []
    sg_counter = 0  # Counter for generating subgraph IDs

    # Detect diagram type from first non-empty line
    diagram_type = ""
    for line in lines:
        stripped = line.strip()
        if stripped:
            diagram_type = stripped.split()[0].lower() if stripped.split() else ""
            break

    is_flowchart = diagram_type in {
        "flowchart", "graph", "flowchart-tb", "flowchart-lr",
        "flowchart-bt", "flowchart-rl", "graph-tb", "graph-lr",
        "graph-bt", "graph-rl",
    }
    is_sequence = diagram_type == "sequencediagram"

    for line in lines:
        if is_flowchart:
            line, sg_counter = _fix_flowchart_line(line, sg_counter)
        elif is_sequence:
            line = _fix_sequence_line(line, line.strip())

        fixed_lines.append(line)

    return "\n".join(fixed_lines)


def _fix_flowchart_line(line: str, sg_counter: int) -> tuple[str, int]:
    """Apply flowchart-specific fixes to a single line.

    Fixes:
    1. Unquoted parentheses in node labels (rectangles)
    2. Unquoted parentheses in diamond conditions
    3. Unquoted parentheses in edge labels
    4. Assignment operator in diamond conditions
    5. Assignment operator in bracket labels
    6. Reserved word "end" as node ID
    7. Style markers (o/x) after --- dividers
    8. Subgraph without ID

    Args:
        line: Single line from the mermaid block.
        sg_counter: Current subgraph ID counter.

    Returns:
        (fixed_line, updated_sg_counter) tuple.
    """
    stripped = line.strip()

    # Fix 1: Unquoted parentheses in node labels
    # A[foo(bar)] -> A["foo(bar)"]
    def _quote_paren_node(m: re.Match) -> str:
        nid, pre, inner, post = m.group(1), m.group(2), m.group(3), m.group(4)
        label = f'{pre}({inner}){post}'
        return f'{nid}["{label}"]'

    line = _UNQUOTED_PAREN_NODE_RE.sub(_quote_paren_node, line)

    # Fix 2: Unquoted parentheses in diamond nodes
    # A{foo(bar)} -> A{"foo(bar)"}
    def _quote_paren_diamond(m: re.Match) -> str:
        nid, pre, inner, post = m.group(1), m.group(2), m.group(3), m.group(4)
        label = f'{pre}({inner}){post}'
        return f'{nid}{{"{label}"}}'

    line = _UNQUOTED_PAREN_DIAMOND_RE.sub(_quote_paren_diamond, line)

    # Fix 3: Unquoted parentheses in edge labels
    # |foo(bar)| -> |"foo(bar)"|
    def _quote_paren_edge(m: re.Match) -> str:
        pre, inner, post = m.group(1), m.group(2), m.group(3)
        label = f'{pre}({inner}){post}'
        return f'|"{label}"|'

    line = _UNQUOTED_PAREN_EDGE_RE.sub(_quote_paren_edge, line)

    # Fix 4: Assignment in diamond conditions
    # A{x = y} -> A{"x = y"}
    def _quote_assign_diamond(m: re.Match) -> str:
        nid, left, right = m.group(1), m.group(2), m.group(3)
        label = f'{left.strip()} = {right.strip()}'
        return f'{nid}{{"{label}"}}'

    line = _ASSIGN_IN_DIAMOND_RE.sub(_quote_assign_diamond, line)

    # Fix 5: Assignment in bracket labels
    # A[x = y] -> A["x = y"]
    def _quote_assign_bracket(m: re.Match) -> str:
        nid, left, right = m.group(1), m.group(2), m.group(3)
        label = f'{left.strip()} = {right.strip()}'
        return f'{nid}["{label}"]'

    line = _ASSIGN_IN_BRACKET_RE.sub(_quote_assign_bracket, line)

    # Fix 6: Reserved word "end" as node ID
    # end[...] -> theEnd[...]
    def _fix_reserved_end(m: re.Match) -> str:
        indent, word, rest = m.group(1), m.group(2), m.group(3)
        return f'{indent}theEnd{rest}'

    line = _RESERVED_END_RE.sub(_fix_reserved_end, line)

    # Fix 7: Style markers after --- dividers
    # ---o or ---x -> --- (remove the marker)
    line = _STYLE_AFTER_DIVIDER_RE.sub(r'\1', line)

    # Fix 8: Subgraph without ID -- add auto-generated ID
    if stripped.lower().startswith("subgraph") and not _has_subgraph_id(stripped):
        sg_counter += 1
        indent = line[: len(line) - len(line.lstrip())]
        title = stripped[len("subgraph"):].strip()
        if title:
            line = f'{indent}subgraph sg_{sg_counter} ["{title}"]'
        else:
            line = f'{indent}subgraph sg_{sg_counter}'

    return line, sg_counter


def _fix_sequence_line(line: str, stripped: str) -> str:
    """Apply sequence diagram-specific fixes to a single line.

    Fixes:
    1. Nested/double quotes in messages
    2. Semicolons in message text

    Args:
        line: Original line with indentation.
        stripped: Stripped version of the line.

    Returns:
        Fixed line.
    """
    # Fix nested quotes: "foo"bar"baz" -> "foobarbaz"
    if '"' in stripped and stripped.count('"') > 2:
        line = _NESTED_QUOTES_RE.sub(r'"\1\2\3"', line)

    # Fix semicolons in messages: ->> B: text; -> ->> B: text
    if ";" in stripped and ("->>" in stripped or "-->>" in stripped):
        line = _SEMICOLON_IN_MSG_RE.sub(r'\1 \2', line)

    return line


def _has_subgraph_id(line: str) -> bool:
    """Check if a subgraph line already has an ID.

    Args:
        line: Stripped subgraph line.

    Returns:
        True if the line has an ID (contains brackets or has two words after 'subgraph').
    """
    after = line[len("subgraph"):].strip()
    if not after:
        return False
    # Has bracket syntax: subgraph id ["title"]
    if "[" in after:
        return True
    # Has two tokens: subgraph id "title" or subgraph id
    parts = after.split(None, 1)
    return len(parts) >= 1 and parts[0].isidentifier()


def _wrap_mermaid_in_details(content: str) -> str:
    """Wrap each mermaid block in a <details> tag with a title.

    The title is derived from the edge/message count in the diagram.

    Args:
        content: Document with mermaid blocks.

    Returns:
        Content with each mermaid block wrapped in <details>/<summary>.
    """

    def _replace_block(m: re.Match) -> str:
        full_block = m.group(0)
        body = m.group(2)

        # Count edges (flowchart) or messages (sequence)
        edge_count = len(re.findall(r'(?:-->|-->>|->>|---|\.\.>)', body))
        msg_count = len(re.findall(r'(?:->>|-->>)', body))
        count = msg_count if msg_count > 0 else edge_count

        # Try to extract title from the diagram
        title_match = re.search(r'(?:title\s+)(.+)', body)
        if title_match:
            title = html.escape(title_match.group(1).strip())
        else:
            # Extract first line after diagram type declaration
            first_lines = [l.strip() for l in body.strip().split("\n")
                          if l.strip() and not l.strip().startswith("%%")]
            diagram_type = first_lines[0] if first_lines else "diagram"
            if count > 0:
                title = f"{html.escape(diagram_type)} ({count} edges)"
            else:
                title = html.escape(diagram_type)

        return (
            f'<details>\n'
            f'<summary>{title}</summary>\n\n'
            f'{full_block}\n\n'
            f'</details>'
        )

    return _MERMAID_BLOCK_RE.sub(_replace_block, content)
