"""Phase 4: Document assembly (no LLM -- deterministic merge)."""

from __future__ import annotations


import json
import logging
import time
from pathlib import Path

from repo_analyzer.config import Config
from repo_analyzer.llm.client import LLMClient
from repo_analyzer.render.mermaid import fix_mermaid_syntax
from repo_analyzer.render.markdown import normalize_headings, generate_toc
from repo_analyzer.render.html import generate_html_report

logger = logging.getLogger("repo_analyzer.phase4")


def run_phase4(
    cfg: Config,
    llm: LLMClient,
    module_analyses: dict[str, str],
    architecture: str,
    cross_flows: str = "",
) -> str:
    """Run Phase 4: assemble final document."""
    from repo_analyzer.analysis.rebuild_guide import generate_rebuild_guide

    logger.info("[Phase 4] Assembling final document ...")

    module_order = sorted(module_analyses.keys())

    normalized_modules: dict[str, str] = {}
    for name, content in module_analyses.items():
        normalized_modules[name] = normalize_headings(content, base_level=4)

    parts: list[str] = []

    parts.append(f"# {cfg.repo_name} -- Reverse Engineering Document\n")
    parts.append(
        '> **Quality Standard**: This document reaches "rebuildable" level -- '
        'a developer can reconstruct a functionally equivalent project from this document alone.'
    )
    parts.append("")

    parts.append("<!-- TOC_PLACEHOLDER -->")
    parts.append("")

    parts.append("---\n")
    parts.append("## 1. Architecture Overview\n")
    parts.append(architecture)

    if cross_flows:
        parts.append("\n---\n")
        parts.append("## 2. Cross-Module End-to-End Flows\n")
        parts.append(
            '> The following flow diagrams show the most important end-to-end business flows, '
            'each spanning multiple modules with complete call chains.\n'
        )
        parts.append(cross_flows)

    parts.append("\n---\n")
    parts.append("## 3. Module Details\n")
    parts.append(
        '> Each module analysis includes: responsibilities, core business flow diagrams (Mermaid), '
        'public interface inventory, core algorithms, data structures, error handling, '
        'boundary conditions, external dependencies, and design decisions.\n'
    )

    for i, name in enumerate(module_order, 1):
        display = name.replace("src_", "").replace("_", "/")
        parts.append(f"### 3.{i} `{display}`\n")
        content = normalized_modules.get(name, "")
        parts.append(content)
        parts.append("")

    parts.append("\n---\n")
    parts.append("## 4. Rebuild Guide\n")
    metadata_file = cfg.analysis_dir / "metadata.json"
    metadata: dict = {}
    if metadata_file.exists():
        with open(metadata_file, encoding="utf-8") as f:
            metadata = json.load(f)
    parts.append(generate_rebuild_guide(str(cfg.repo_path), metadata))

    parts.append(
        f"\n---\n\n*Generated by repo-analyzer v2.0 | LLM: {llm.model} | "
        f"Date: {time.strftime('%Y-%m-%d %H:%M')}*\n"
    )

    final = "\n".join(parts)

    toc = generate_toc(final)
    final = final.replace("<!-- TOC_PLACEHOLDER -->", toc)
    final = fix_mermaid_syntax(final)

    out_path = cfg.output or (cfg.repo_path.parent / f"{cfg.repo_name}-analysis.md")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(final, encoding="utf-8")
    logger.info("  Markdown -> %s (%d chars)", out_path, len(final))

    html = generate_html_report(final, cfg.repo_name, llm.model)
    html_path = out_path.with_suffix(".html")
    html_path.write_text(html, encoding="utf-8")
    logger.info("  HTML     -> %s (%d chars)", html_path, len(html))

    modules_out = cfg.analysis_dir / "module_analyses"
    if modules_out.exists():
        dest_modules = out_path.parent / f"{cfg.repo_name}-modules"
        dest_modules.mkdir(parents=True, exist_ok=True)
        for mod_file in sorted(modules_out.glob("*.md")):
            content = mod_file.read_text(encoding="utf-8")
            content = normalize_headings(content, base_level=1)
            dest = dest_modules / mod_file.name
            dest.write_text(content, encoding="utf-8")
        logger.info("  Modules  -> %s/ (%d files)", dest_modules, len(list(dest_modules.glob("*.md"))))

    outputs_file = cfg.analysis_dir / "outputs.json"
    if outputs_file.exists():
        with open(outputs_file, encoding="utf-8") as f:
            identified_outputs = json.load(f)

        if identified_outputs:
            from repo_analyzer.phases.output_id import generate_io_flow_document
            io_md = generate_io_flow_document(identified_outputs, normalized_modules, cfg.repo_name)
            io_md = fix_mermaid_syntax(io_md)

            io_md_path = out_path.parent / f"{cfg.repo_name}-io-flows.md"
            io_md_path.write_text(io_md, encoding="utf-8")
            logger.info("  IO Flows -> %s (%d chars)", io_md_path, len(io_md))

            io_html = generate_html_report(io_md, f"{cfg.repo_name} IO Flows", llm.model)
            io_html_path = out_path.parent / f"{cfg.repo_name}-io-flows.html"
            io_html_path.write_text(io_html, encoding="utf-8")
            logger.info("  IO HTML  -> %s (%d chars)", io_html_path, len(io_html))

    return final
